title: Frontend Engineering Onboarding | The Iron Yard - Washington DC
project_name: Frontend Engineering
class_logo: img/fee.png
description: >
  The Iron Yard - Washington DC
repository_url: https://github.com/tiydc/fee-onboarding
repository_shorthand: tiydc/fee-onboarding
class_github_org: https://github.com/tiydc
baseurl: /fee-onboarding
instructor_name: Jordan Kasper
instructor_email: jordan.kasper@theironyard.com
instructor_url: https://github.com/jakerella
instructor_photo: https://jordankasper.com/images/jordan_bw.jpg
cd_name_informal: Su
cd_name: Su Kim
cd_email: su@theironyard.com
collections:
  sections:
    output: true
